/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TdDateInput: typeof import('./components/UI/TdDateInput.vue')['default']
    TdDatePicker: typeof import('./components/UI/TdDatePicker.vue')['default']
    TdDictionaryListItem: typeof import('./components/UI/TdDictionaryListItem.vue')['default']
    TdLayout: typeof import('./components/UI/TdLayout.vue')['default']
    TdMask: typeof import('./components/UI/TdMask.vue')['default']
    TdTimeInput: typeof import('./components/UI/TdTimeInput.vue')['default']
    TrainingCard: typeof import('./components/TrainingCard.vue')['default']
    TrainingExerciseCard: typeof import('./components/TrainingExerciseCard.vue')['default']
  }
}
