/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/equipments/': RouteRecordInfo<'/equipments/', '/equipments', Record<never, never>, Record<never, never>>,
    '/equipments/[id]': RouteRecordInfo<'/equipments/[id]', '/equipments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/exercises/': RouteRecordInfo<'/exercises/', '/exercises', Record<never, never>, Record<never, never>>,
    '/exercises/[id]': RouteRecordInfo<'/exercises/[id]', '/exercises/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/muscles/': RouteRecordInfo<'/muscles/', '/muscles', Record<never, never>, Record<never, never>>,
    '/muscles/[id]': RouteRecordInfo<'/muscles/[id]', '/muscles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/tags/[id]': RouteRecordInfo<'/tags/[id]', '/tags/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/training-exercises/': RouteRecordInfo<'/training-exercises/', '/training-exercises', Record<never, never>, Record<never, never>>,
    '/training-exercises/[id]': RouteRecordInfo<'/training-exercises/[id]', '/training-exercises/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/trainings/': RouteRecordInfo<'/trainings/', '/trainings', Record<never, never>, Record<never, never>>,
    '/trainings/[id]': RouteRecordInfo<'/trainings/[id]', '/trainings/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
