name: Build and Signed release apk

on:
  push:
    branches: [ "master" ]

jobs:
  Build-Release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build and sync web code
      run: |
        npm install
        npm run build:android
        cd ./src-capacitor
        npx cap sync android

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./src-capacitor/android/gradlew

    - name: Build release APK
      run: |
        cd ./src-capacitor/android
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
