name: Build and Signed release apk

on:
  push:
    branches: [ "master" ]

jobs:
  Build-Web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Build
      run: |
        npm i
        npx run build:capacitor
